export const ACCOUNT_CATEGORIES = {
  AIRLINE: 'Airline',
  HOTEL: 'Hotel',
  CREDIT_CARD: 'Credit Card',
};

export const AIRLINE_PROGRAMS = [
  'American Airlines AAdvantage',
  'Delta SkyMiles',
  'United MileagePlus',
  'Southwest Rapid Rewards',
  'JetBlue TrueBlue',
  'Alaska Airlines MileagePlan',
  'British Airways Avios',
  'Air Canada Aeroplan',
  'Emirates Skywards',
  'Etihad Guest',
  'Lufthansa Miles & More',
  'Qatar Airways Privilege Club',
  'Singapore Airlines KrisFlyer',
  'HawaiianMiles',
  'Air France-KLM Flying Blue',
  'Turkish Airlines Miles&Smiles',
  'Virgin Atlantic Flying Club',
  'Cathay Pacific Asia Miles',
  'Korean Air Skypass',
  'Japan Airlines Mileage Bank',
  'ANA Mileage Club',
  'EVA Air Infinity MileageLands',
  'Asiana Club',
  'Malaysia Airlines Enrich',
  'Thai Airways Royal Orchid Plus',
  'Vietnam Airlines Lotusmiles',
  'Philippine Airlines Mabuhay Miles',
  'Garuda Indonesia GarudaMiles',
  'Qantas Frequent Flyer',
  'Virgin Australia Velocity',
  'Air New Zealand Airpoints',
  'Fiji Airways Tabua Club',
  'Avianca LifeMiles',
  'LATAM Pass',
  'GOL Smiles',
  'Azul TudoAzul',
  'Aeromexico Club Premier',
  'Volaris Club Volaris',
  'Interjet Club Interjet',
  'WestJet Rewards',
  'Frontier Miles',
  'Spirit Airlines Free Spirit',
  'Allegiant Air Allways Rewards',
  'Sun Country Airlines Ufly Rewards',
  'Breeze Airways BreezePoints',
  'Avelo Airlines Avelo Rewards',
  'Other',
];

export const HOTEL_PROGRAMS = [
  'Marriott Bonvoy',
  'Hilton Honors',
  'World of Hyatt',
  'IHG One Rewards',
  'Wyndham Rewards',
  'Choice Privileges',
  'Accor Live Limitless',
  'Best Western Rewards',
  'Radisson Rewards Americas',
  'Omni Select Guest',
  'Loews YouFirst',
  'MGM Rewards',
  'Caesars Rewards',
  'Wynn Rewards',
  'Mirage M Life Rewards',
  'Venetian Grazie Rewards',
  'Mandarin Oriental Fan Club',
  'Four Seasons Preferred Partner',
  'St. Regis Starwood Preferred Guest',
  'Ritz-Carlton Rewards',
  'Shangri-La Golden Circle',
  'Peninsula PenClub',
  'Fairmont President\'s Club',
  'Raffles Ambassadors',
  'Swissôtel Circle',
  'Sofitel Le Club',
  'Pullman Le Club',
  'Mövenpick Rewards',
  'Banyan Tree Banyan Tree Club',
  'Anantara Anantara Golden Triangle',
  'Minor Hotels DISCOVERY',
  'NH Rewards',
  'Other',
];
export const CREDIT_CARD_PROGRAMS = [
  'American Express Membership Rewards',
  'Chase Ultimate Rewards',
  'Capital One Miles',
  'Citi ThankYou Points',
  'Bilt Rewards',
  'Brex',
  'Bank of America Travel Rewards',
  'Barclays Arrival Rewards',
  'Discover Miles',
  'HSBC Rewards',
  'TD Rewards',
  'Wells Fargo Rewards',
  'US Bank Altitude Rewards',
  'PNC Points',
  'Fifth Third Rewards',
  'KeyBank Rewards',
  'Regions LifeGreen Rewards',
  'SunTrust Rewards',
  'Other',
];

// Placeholder for specific cards. In a real app, this might come from a DB.
export const CREDIT_CARDS_BY_PROGRAM: { [key: string]: string[] } = {
  'American Express Membership Rewards': [
    'Platinum Card',
    'Gold Card',
    'Green Card',
    'EveryDay Preferred Credit Card',
    'Other',
  ],
  'Chase Ultimate Rewards': [
    'Sapphire Reserve',
    'Sapphire Preferred',
    'Freedom Flex',
    'Freedom Unlimited',
    'Ink Business Preferred',
    'Ink Business Cash',
    'Ink Business Unlimited',
    'Other',
  ],
  'Capital One Miles': [
    'Venture X',
    'Venture',
    'VentureOne',
    'Savor',
    'SavorOne',
    'Other'
  ],
  'Citi ThankYou Points': [
    'Prestige',
    'Premier',
    'Rewards+',
    'Custom Cash',
    'Other'
  ]
}; 